test:
  imports:
    - open_notebook
  commands:
    - pip check
    - open-notebook --help
    - nopen --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/usnistgov/open-notebook
  summary: Command line program to open jupyter notebooks from single server
  description: |
    Command line program to open jupyter notebooks from single server
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
